<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 22/09/2016
 */
?>
<main>
    <div class="title_cadastro center-align">
        <h1><i class="material-icons prefix">done</i> <span style="vertical-align: text-top;">Cadastro ativado.</span></h1>
    </div>
    <div class="container home-margin-top">
        <div class="col s12">
            A sua conta foi ativada, acesse agora mesmo seu painel.
        </div>
    </div>
</main>

