<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 22/09/2016
 */
?>
<main>
    <div class="title_cadastro center-align">
        <h1><i class="material-icons prefix">assignment_late</i> <span style="vertical-align: text-top;">Oops! Link inválido</span></h1>
    </div>
    <div class="container home-margin-top">
        <div class="col s12">
            Desculpe! Mas este link já foi usado.
        </div>
    </div>
</main>