<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 21/09/2016
 */
?>
<main>
    <div class="title_cadastro center-align">
        <h1><i class="material-icons prefix">done</i> <span style="vertical-align: text-top;">Parabéns! Agora você é um associado <b>Acheimed</b>.</span></h1>
    </div>
    <div class="container home-margin-top">
        <div class="col s12">
            Acesse o seu email para ativar a sua conta.
        </div>
    </div>
</main>

