<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 17/08/2016
 */
?>
<main>
    <div class="parallax-container">
        <div class="section no-pad-bot">
            <div class="content_paralax">
                <div class="container">
                    <div class="row">
                        <div class="col m8 offset-m2 s12">
                            <div class="text-paralax-home center-align">
                                <h1 >Até 80% de redução no valor em<br>
                                    Consultas ou Exames Médicos</h1>

                                <p>Através de nossa plataforma, você econtra os médicos e<br>
                                    clínicas associados mais próximos com condições especiais de pagamento.</p>
                                <h2>O que você procura?</h2>
                            </div>
                            <div class="destaque-paralax">
                                <div class="row">
                                    <div class="col m3 s12 center-on-small-only">
                                        <a class="btn-paralax" href="">
                                            <img class="center-block responsive-img" src="<?=parent::$imagePath.'esteto.png';?>" alt=""><br>
                                            CONSULTAS MÉDICAS
                                        </a>
                                    </div>
                                    <div class="col m3 s12 center-on-small-only">
                                        <a class="btn-paralax" href="">
                                            <img class="center-block responsive-img" src="<?=parent::$imagePath.'microscopio.png';?>" alt=""><br>
                                            EXAMES LABORATORIAIS</a>
                                    </div>
                                    <div class="col m3 s12 center-on-small-only">
                                        <a class="btn-paralax" href="">
                                            <img class="center-block responsive-img" src="<?=parent::$imagePath.'relatorio.png';?>" alt=""><br>
                                            EXAMES DE IMAGEM</a>
                                    </div>
                                    <div class="col m3 s12 center-on-small-only">
                                        <a class="btn-paralax" href="">
                                            <img class="center-block responsive-img" src="<?=parent::$imagePath.'bisturi.png';?>" alt=""><br>
                                            PROCEDIMENTOS MÉDICOS</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="parallax"><img src="<?=parent::$imagePath.'banner_home.jpg';?>"></div>
    </div>
    <div class="bg_busca">
        <div class="container">
            <div class="col m12">
                <form action="">
                    <div class="row">
                        <div class="input-field col m3 offset-m2 s12">
                            <select class="select-search">
                                <option value="" >Selecione a especialidade</option>
                                <option value="1">Option 1</option>
                                <option value="2">Option 2</option>
                                <option value="3">Option 3</option>
                            </select>
                        </div>
                        <div class="input-field col m3 s12">
                            <select class="select-search">
                                <option value="" >Localização</option>
                                <option value="1">Option 1</option>
                                <option value="2">Option 2</option>
                                <option value="3">Option 3</option>
                            </select>
                        </div>
                        <div class="col m2 s12 center" style="margin-top: 16px">
                            <button class="btn_menu" >Encontre <i class="mdi mdi-magnify"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="bg_use">
        <div class="container">
            <div class="row">
                <div class="col m12 s12">
                    <div class="title-use center">
                        <h1>Como funciona?</h1>
                    </div>
                    <div class="processos">
                        <div class="row">
                            <div class="col m3 s12">
                                <img class="center-block" src="<?=parent::$imagePath.'lupa.png';?>" alt=""><br>
                                <div class="numero">1.</div>
                                <div class="text_processos">
                                    Encontre a consulta<br> ou exame que procura
                                </div>
                            </div>
                            <div class="col m3 s12">
                                <img class="center-block" src="<?=parent::$imagePath.'carta.png';?>" alt=""><br>
                                <div class="numero">2.</div>
                                <div class="text_processos">
                                    Realize o pagamento<br>
                                    de nosso e-Card

                                </div>
                            </div>
                            <div class="col m3 s12">
                                <img class="center-block" src="<?=parent::$imagePath.'tel.png';?>" alt=""><br>
                                <div class="numero">3.</div>
                                <div class="text_processos">
                                    Entre em contato com a<br>
                                    clinica ou Médico escolhido<br>
                                    e agende o melhor horário.

                                </div>
                            </div>
                            <div class="col m3 s12">
                                <img class="center-block" src="<?=parent::$imagePath.'recebimento.png';?>" alt=""><br>
                                <div class="numero">4.</div>
                                <div class="text_processos">
                                    Apresente o e-Card e<br>
                                    garanta o valor reduzido.

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="faixa-home"></div>
    <div class="bg_centro_med">
        <div class="container">
            <div class="row">
                <div class="col m6 s12">
                    <img class="center-block responsive-img" src="<?=parent::$imagePath.'stetos_g.jpg';?>" alt="">
                </div>
                <div class="col m6 s12">
                    <div class="text_centro_med">
                        <h1>Você tem um centro médico ou
                            é um profissional da saúde?</h1>
                        <p>- Comece a ganhar mais pacientes melhorando sua reputação online.
                            Doctoralia é onde mais se procuram médicos hoje em dia.<br>
                            <span>Deixe que lhe encontrem!</span>
                        </p>
                        <a class="btn_menu" >Saiba mais</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
