<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 17/08/2016
 */
?>
<main class="valign-wrapper" style="margin-top: 15px;">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="center-align">
                    <h3 class="valign">
                        <i class="material-icons">portable_wifi_off</i> <span style="vertical-align: super">Falha de conexão com o banco de dados</span>
                    </h3><br>
                    <span>
                        <p>
                            Encontramos uma falha ao tentar se conectar com o banco de dados.
                            Este problema pode ter ocorrido por uma interrupção da conexão.
                        </p>
                        <br>
                        <p>
                            Por favor, atualize a página. Se o problema persistir entre em contato com o
                            administrador do site.
                        </p>
                    </span>
                </div>
            </div>
        </div>
    </div>
</main>
