<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 17/08/2016
 */
?>
<main class="valign-wrapper" style="margin-top: 15px;">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="center-align">
                    <h3 class="valign">
                        Página não encontada!
                    </h3>
                </div>
            </div>
        </div>
    </div>
</main>
