<?php
/**
 * Created by Grupo B+M
 * User: Esdras Castro
 * Date: 17/08/2016
 */
?>
<main class="valign-wrapper">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="center-align">
                    <h3 class="valign">
                        Sem Conexão
                    </h3><br>
                    <span>
                        Verifique a sua conexão com a internet.
                    </span>
                </div>
            </div>
        </div>
    </div>
</main>
